services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    volumes:
      - ${DATA_PATH}/backrest/data:/data
      - ${DATA_PATH}/backrest/config:/config
      - ${DATA_PATH}/backrest/cache:/cache
      - ${DATA_PATH}:/userdata
      - ${DATA_PATH}/rclone/config:/root/.config/rclone
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TZ=America/Sao_Paulo
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backrest.rule=Host(`backrest.masahome`)"
      - "traefik.http.routers.backrest.entrypoints=web"
      - "traefik.http.services.backrest.loadbalancer.server.port=9898"

networks:
  proxy:
    external: true
