services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/firefly/upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.rule=Host(`firefly.masahome`)"
      - "traefik.http.routers.firefly.entrypoints=web"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
    depends_on:
      - db

  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - ${DATA_PATH}/firefly/db:/var/lib/mysql

  cron:
    image: alpine
    restart: unless-stopped
    container_name: firefly_iii_cron
    env_file: .env
    command: sh -c "
      apk add tzdata && \
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -q0- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\"
      | crontab - && \
      crond -f -L /dev/stdout"
    networks:
      - firefly_iii
    depends_on:
      - app

networks:
  firefly_iii:
    driver: bridge
  proxy:
    external: true
